###
GET http://localhost:3000/usuarios

###
GET http://localhost:3000/usuarios/3


###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nome": "Martha Lacerda"
}

###
PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
  "nome": "Mudei o nome"
}

###
DELETE http://localhost:3000/usuarios/2

###
GET http://localhost:3000/saudacao/Martinha
